=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  class Checkout < ApiModelBase
    attr_accessor :checkout_uuid

    attr_accessor :merchant_order_id

    attr_accessor :status

    attr_accessor :transaction_ref

    attr_accessor :checkout_url

    attr_accessor :merchant_expires_at

    attr_accessor :captured_at

    attr_accessor :return_url

    attr_accessor :cancel_url

    attr_accessor :amount

    attr_accessor :currency

    attr_accessor :service_fee

    attr_accessor :refunded_amount

    attr_accessor :merchant_processor_fee

    attr_accessor :merchant_service_fee

    attr_accessor :last_refund_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'checkout_uuid' => :'checkout_uuid',
        :'merchant_order_id' => :'merchant_order_id',
        :'status' => :'status',
        :'transaction_ref' => :'transaction_ref',
        :'checkout_url' => :'checkout_url',
        :'merchant_expires_at' => :'merchant_expires_at',
        :'captured_at' => :'captured_at',
        :'return_url' => :'return_url',
        :'cancel_url' => :'cancel_url',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'service_fee' => :'service_fee',
        :'refunded_amount' => :'refunded_amount',
        :'merchant_processor_fee' => :'merchant_processor_fee',
        :'merchant_service_fee' => :'merchant_service_fee',
        :'last_refund_at' => :'last_refund_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'checkout_uuid' => :'String',
        :'merchant_order_id' => :'String',
        :'status' => :'String',
        :'transaction_ref' => :'String',
        :'checkout_url' => :'String',
        :'merchant_expires_at' => :'Time',
        :'captured_at' => :'Time',
        :'return_url' => :'String',
        :'cancel_url' => :'String',
        :'amount' => :'Integer',
        :'currency' => :'String',
        :'service_fee' => :'Fee',
        :'refunded_amount' => :'Integer',
        :'merchant_processor_fee' => :'Integer',
        :'merchant_service_fee' => :'Integer',
        :'last_refund_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'merchant_order_id',
        :'transaction_ref',
        :'merchant_expires_at',
        :'captured_at',
        :'return_url',
        :'cancel_url',
        :'last_refund_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MaytesApiClient::Checkout` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MaytesApiClient::Checkout`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'checkout_uuid')
        self.checkout_uuid = attributes[:'checkout_uuid']
      else
        self.checkout_uuid = nil
      end

      if attributes.key?(:'merchant_order_id')
        self.merchant_order_id = attributes[:'merchant_order_id']
      else
        self.merchant_order_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'transaction_ref')
        self.transaction_ref = attributes[:'transaction_ref']
      else
        self.transaction_ref = nil
      end

      if attributes.key?(:'checkout_url')
        self.checkout_url = attributes[:'checkout_url']
      else
        self.checkout_url = nil
      end

      if attributes.key?(:'merchant_expires_at')
        self.merchant_expires_at = attributes[:'merchant_expires_at']
      else
        self.merchant_expires_at = nil
      end

      if attributes.key?(:'captured_at')
        self.captured_at = attributes[:'captured_at']
      else
        self.captured_at = nil
      end

      if attributes.key?(:'return_url')
        self.return_url = attributes[:'return_url']
      else
        self.return_url = nil
      end

      if attributes.key?(:'cancel_url')
        self.cancel_url = attributes[:'cancel_url']
      else
        self.cancel_url = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'service_fee')
        self.service_fee = attributes[:'service_fee']
      else
        self.service_fee = nil
      end

      if attributes.key?(:'refunded_amount')
        self.refunded_amount = attributes[:'refunded_amount']
      else
        self.refunded_amount = nil
      end

      if attributes.key?(:'merchant_processor_fee')
        self.merchant_processor_fee = attributes[:'merchant_processor_fee']
      else
        self.merchant_processor_fee = nil
      end

      if attributes.key?(:'merchant_service_fee')
        self.merchant_service_fee = attributes[:'merchant_service_fee']
      else
        self.merchant_service_fee = nil
      end

      if attributes.key?(:'last_refund_at')
        self.last_refund_at = attributes[:'last_refund_at']
      else
        self.last_refund_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @checkout_uuid.nil?
        invalid_properties.push('invalid value for "checkout_uuid", checkout_uuid cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @checkout_url.nil?
        invalid_properties.push('invalid value for "checkout_url", checkout_url cannot be nil.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @service_fee.nil?
        invalid_properties.push('invalid value for "service_fee", service_fee cannot be nil.')
      end

      if @refunded_amount.nil?
        invalid_properties.push('invalid value for "refunded_amount", refunded_amount cannot be nil.')
      end

      if @refunded_amount < 0
        invalid_properties.push('invalid value for "refunded_amount", must be greater than or equal to 0.')
      end

      if @merchant_processor_fee.nil?
        invalid_properties.push('invalid value for "merchant_processor_fee", merchant_processor_fee cannot be nil.')
      end

      if @merchant_processor_fee < 0
        invalid_properties.push('invalid value for "merchant_processor_fee", must be greater than or equal to 0.')
      end

      if @merchant_service_fee.nil?
        invalid_properties.push('invalid value for "merchant_service_fee", merchant_service_fee cannot be nil.')
      end

      if @merchant_service_fee < 0
        invalid_properties.push('invalid value for "merchant_service_fee", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @checkout_uuid.nil?
      return false if @status.nil?
      return false if @checkout_url.nil?
      return false if @amount.nil?
      return false if @currency.nil?
      return false if @service_fee.nil?
      return false if @refunded_amount.nil?
      return false if @refunded_amount < 0
      return false if @merchant_processor_fee.nil?
      return false if @merchant_processor_fee < 0
      return false if @merchant_service_fee.nil?
      return false if @merchant_service_fee < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] checkout_uuid Value to be assigned
    def checkout_uuid=(checkout_uuid)
      if checkout_uuid.nil?
        fail ArgumentError, 'checkout_uuid cannot be nil'
      end

      @checkout_uuid = checkout_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] checkout_url Value to be assigned
    def checkout_url=(checkout_url)
      if checkout_url.nil?
        fail ArgumentError, 'checkout_url cannot be nil'
      end

      @checkout_url = checkout_url
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] service_fee Value to be assigned
    def service_fee=(service_fee)
      if service_fee.nil?
        fail ArgumentError, 'service_fee cannot be nil'
      end

      @service_fee = service_fee
    end

    # Custom attribute writer method with validation
    # @param [Object] refunded_amount Value to be assigned
    def refunded_amount=(refunded_amount)
      if refunded_amount.nil?
        fail ArgumentError, 'refunded_amount cannot be nil'
      end

      if refunded_amount < 0
        fail ArgumentError, 'invalid value for "refunded_amount", must be greater than or equal to 0.'
      end

      @refunded_amount = refunded_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_processor_fee Value to be assigned
    def merchant_processor_fee=(merchant_processor_fee)
      if merchant_processor_fee.nil?
        fail ArgumentError, 'merchant_processor_fee cannot be nil'
      end

      if merchant_processor_fee < 0
        fail ArgumentError, 'invalid value for "merchant_processor_fee", must be greater than or equal to 0.'
      end

      @merchant_processor_fee = merchant_processor_fee
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_service_fee Value to be assigned
    def merchant_service_fee=(merchant_service_fee)
      if merchant_service_fee.nil?
        fail ArgumentError, 'merchant_service_fee cannot be nil'
      end

      if merchant_service_fee < 0
        fail ArgumentError, 'invalid value for "merchant_service_fee", must be greater than or equal to 0.'
      end

      @merchant_service_fee = merchant_service_fee
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          checkout_uuid == o.checkout_uuid &&
          merchant_order_id == o.merchant_order_id &&
          status == o.status &&
          transaction_ref == o.transaction_ref &&
          checkout_url == o.checkout_url &&
          merchant_expires_at == o.merchant_expires_at &&
          captured_at == o.captured_at &&
          return_url == o.return_url &&
          cancel_url == o.cancel_url &&
          amount == o.amount &&
          currency == o.currency &&
          service_fee == o.service_fee &&
          refunded_amount == o.refunded_amount &&
          merchant_processor_fee == o.merchant_processor_fee &&
          merchant_service_fee == o.merchant_service_fee &&
          last_refund_at == o.last_refund_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [checkout_uuid, merchant_order_id, status, transaction_ref, checkout_url, merchant_expires_at, captured_at, return_url, cancel_url, amount, currency, service_fee, refunded_amount, merchant_processor_fee, merchant_service_fee, last_refund_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
