=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  class CheckoutCreated < ApiModelBase
    attr_accessor :checkout_uuid

    attr_accessor :status

    attr_accessor :checkout_url

    attr_accessor :expires_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'checkout_uuid' => :'checkout_uuid',
        :'status' => :'status',
        :'checkout_url' => :'checkout_url',
        :'expires_at' => :'expires_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'checkout_uuid' => :'String',
        :'status' => :'String',
        :'checkout_url' => :'String',
        :'expires_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MaytesApiClient::CheckoutCreated` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MaytesApiClient::CheckoutCreated`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'checkout_uuid')
        self.checkout_uuid = attributes[:'checkout_uuid']
      else
        self.checkout_uuid = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'checkout_url')
        self.checkout_url = attributes[:'checkout_url']
      else
        self.checkout_url = nil
      end

      if attributes.key?(:'expires_at')
        self.expires_at = attributes[:'expires_at']
      else
        self.expires_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @checkout_uuid.nil?
        invalid_properties.push('invalid value for "checkout_uuid", checkout_uuid cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @checkout_url.nil?
        invalid_properties.push('invalid value for "checkout_url", checkout_url cannot be nil.')
      end

      if @expires_at.nil?
        invalid_properties.push('invalid value for "expires_at", expires_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @checkout_uuid.nil?
      return false if @status.nil?
      return false if @checkout_url.nil?
      return false if @expires_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] checkout_uuid Value to be assigned
    def checkout_uuid=(checkout_uuid)
      if checkout_uuid.nil?
        fail ArgumentError, 'checkout_uuid cannot be nil'
      end

      @checkout_uuid = checkout_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] checkout_url Value to be assigned
    def checkout_url=(checkout_url)
      if checkout_url.nil?
        fail ArgumentError, 'checkout_url cannot be nil'
      end

      @checkout_url = checkout_url
    end

    # Custom attribute writer method with validation
    # @param [Object] expires_at Value to be assigned
    def expires_at=(expires_at)
      if expires_at.nil?
        fail ArgumentError, 'expires_at cannot be nil'
      end

      @expires_at = expires_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          checkout_uuid == o.checkout_uuid &&
          status == o.status &&
          checkout_url == o.checkout_url &&
          expires_at == o.expires_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [checkout_uuid, status, checkout_url, expires_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
