=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  class CreateCheckoutRequest < ApiModelBase
    attr_accessor :merchant_order_id

    attr_accessor :merchant_expires_at

    attr_accessor :total_amount

    attr_accessor :currency

    attr_accessor :return_url

    attr_accessor :cancel_url

    attr_accessor :items

    attr_accessor :fees

    attr_accessor :discounts

    attr_accessor :tax

    attr_accessor :shipping_amount

    attr_accessor :customer_data

    attr_accessor :metadata

    attr_accessor :allocation_model

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'merchant_order_id' => :'merchant_order_id',
        :'merchant_expires_at' => :'merchant_expires_at',
        :'total_amount' => :'total_amount',
        :'currency' => :'currency',
        :'return_url' => :'return_url',
        :'cancel_url' => :'cancel_url',
        :'items' => :'items',
        :'fees' => :'fees',
        :'discounts' => :'discounts',
        :'tax' => :'tax',
        :'shipping_amount' => :'shipping_amount',
        :'customer_data' => :'customer_data',
        :'metadata' => :'metadata',
        :'allocation_model' => :'allocation_model'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'merchant_order_id' => :'String',
        :'merchant_expires_at' => :'Time',
        :'total_amount' => :'Integer',
        :'currency' => :'String',
        :'return_url' => :'String',
        :'cancel_url' => :'String',
        :'items' => :'Array<LineItem>',
        :'fees' => :'Array<CheckoutFee>',
        :'discounts' => :'Array<CheckoutDiscount>',
        :'tax' => :'Tax',
        :'shipping_amount' => :'Integer',
        :'customer_data' => :'CustomerData',
        :'metadata' => :'Hash<String, Object>',
        :'allocation_model' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'merchant_order_id',
        :'merchant_expires_at',
        :'fees',
        :'discounts',
        :'tax',
        :'shipping_amount',
        :'customer_data',
        :'metadata',
        :'allocation_model'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MaytesApiClient::CreateCheckoutRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MaytesApiClient::CreateCheckoutRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'merchant_order_id')
        self.merchant_order_id = attributes[:'merchant_order_id']
      end

      if attributes.key?(:'merchant_expires_at')
        self.merchant_expires_at = attributes[:'merchant_expires_at']
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      else
        self.total_amount = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'return_url')
        self.return_url = attributes[:'return_url']
      else
        self.return_url = nil
      end

      if attributes.key?(:'cancel_url')
        self.cancel_url = attributes[:'cancel_url']
      else
        self.cancel_url = nil
      end

      if attributes.key?(:'items')
        if (value = attributes[:'items']).is_a?(Array)
          self.items = value
        end
      else
        self.items = nil
      end

      if attributes.key?(:'fees')
        if (value = attributes[:'fees']).is_a?(Array)
          self.fees = value
        end
      end

      if attributes.key?(:'discounts')
        if (value = attributes[:'discounts']).is_a?(Array)
          self.discounts = value
        end
      end

      if attributes.key?(:'tax')
        self.tax = attributes[:'tax']
      end

      if attributes.key?(:'shipping_amount')
        self.shipping_amount = attributes[:'shipping_amount']
      end

      if attributes.key?(:'customer_data')
        self.customer_data = attributes[:'customer_data']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'allocation_model')
        self.allocation_model = attributes[:'allocation_model']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @total_amount.nil?
        invalid_properties.push('invalid value for "total_amount", total_amount cannot be nil.')
      end

      if @total_amount <= 0
        invalid_properties.push('invalid value for "total_amount", must be greater than 0.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if @currency !~ pattern
        invalid_properties.push("invalid value for \"currency\", must conform to the pattern #{pattern}.")
      end

      if @return_url.nil?
        invalid_properties.push('invalid value for "return_url", return_url cannot be nil.')
      end

      if @cancel_url.nil?
        invalid_properties.push('invalid value for "cancel_url", cancel_url cannot be nil.')
      end

      if @items.nil?
        invalid_properties.push('invalid value for "items", items cannot be nil.')
      end

      if @items.length < 1
        invalid_properties.push('invalid value for "items", number of items must be greater than or equal to 1.')
      end

      if !@shipping_amount.nil? && @shipping_amount < 0
        invalid_properties.push('invalid value for "shipping_amount", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @total_amount.nil?
      return false if @total_amount <= 0
      return false if @currency.nil?
      return false if @currency !~ Regexp.new(/^[A-Z]{3}$/)
      return false if @return_url.nil?
      return false if @cancel_url.nil?
      return false if @items.nil?
      return false if @items.length < 1
      return false if !@shipping_amount.nil? && @shipping_amount < 0
      allocation_model_validator = EnumAttributeValidator.new('String', ["basic_amount", "item_assignment"])
      return false unless allocation_model_validator.valid?(@allocation_model)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] total_amount Value to be assigned
    def total_amount=(total_amount)
      if total_amount.nil?
        fail ArgumentError, 'total_amount cannot be nil'
      end

      if total_amount <= 0
        fail ArgumentError, 'invalid value for "total_amount", must be greater than 0.'
      end

      @total_amount = total_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if currency !~ pattern
        fail ArgumentError, "invalid value for \"currency\", must conform to the pattern #{pattern}."
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] return_url Value to be assigned
    def return_url=(return_url)
      if return_url.nil?
        fail ArgumentError, 'return_url cannot be nil'
      end

      @return_url = return_url
    end

    # Custom attribute writer method with validation
    # @param [Object] cancel_url Value to be assigned
    def cancel_url=(cancel_url)
      if cancel_url.nil?
        fail ArgumentError, 'cancel_url cannot be nil'
      end

      @cancel_url = cancel_url
    end

    # Custom attribute writer method with validation
    # @param [Object] items Value to be assigned
    def items=(items)
      if items.nil?
        fail ArgumentError, 'items cannot be nil'
      end

      if items.length < 1
        fail ArgumentError, 'invalid value for "items", number of items must be greater than or equal to 1.'
      end

      @items = items
    end

    # Custom attribute writer method with validation
    # @param [Object] shipping_amount Value to be assigned
    def shipping_amount=(shipping_amount)
      if !shipping_amount.nil? && shipping_amount < 0
        fail ArgumentError, 'invalid value for "shipping_amount", must be greater than or equal to 0.'
      end

      @shipping_amount = shipping_amount
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] allocation_model Object to be assigned
    def allocation_model=(allocation_model)
      validator = EnumAttributeValidator.new('String', ["basic_amount", "item_assignment"])
      unless validator.valid?(allocation_model)
        fail ArgumentError, "invalid value for \"allocation_model\", must be one of #{validator.allowable_values}."
      end
      @allocation_model = allocation_model
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          merchant_order_id == o.merchant_order_id &&
          merchant_expires_at == o.merchant_expires_at &&
          total_amount == o.total_amount &&
          currency == o.currency &&
          return_url == o.return_url &&
          cancel_url == o.cancel_url &&
          items == o.items &&
          fees == o.fees &&
          discounts == o.discounts &&
          tax == o.tax &&
          shipping_amount == o.shipping_amount &&
          customer_data == o.customer_data &&
          metadata == o.metadata &&
          allocation_model == o.allocation_model
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [merchant_order_id, merchant_expires_at, total_amount, currency, return_url, cancel_url, items, fees, discounts, tax, shipping_amount, customer_data, metadata, allocation_model].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
