=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  class Fee < ApiModelBase
    attr_accessor :gross

    attr_accessor :discount

    attr_accessor :net

    attr_accessor :breakdown

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'gross' => :'gross',
        :'discount' => :'discount',
        :'net' => :'net',
        :'breakdown' => :'breakdown'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'gross' => :'Integer',
        :'discount' => :'Integer',
        :'net' => :'Integer',
        :'breakdown' => :'Array<FeeBreakdownLine>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MaytesApiClient::Fee` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MaytesApiClient::Fee`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'gross')
        self.gross = attributes[:'gross']
      else
        self.gross = nil
      end

      if attributes.key?(:'discount')
        self.discount = attributes[:'discount']
      else
        self.discount = nil
      end

      if attributes.key?(:'net')
        self.net = attributes[:'net']
      else
        self.net = nil
      end

      if attributes.key?(:'breakdown')
        if (value = attributes[:'breakdown']).is_a?(Array)
          self.breakdown = value
        end
      else
        self.breakdown = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @gross.nil?
        invalid_properties.push('invalid value for "gross", gross cannot be nil.')
      end

      if @gross < 0
        invalid_properties.push('invalid value for "gross", must be greater than or equal to 0.')
      end

      if @discount.nil?
        invalid_properties.push('invalid value for "discount", discount cannot be nil.')
      end

      if @discount < 0
        invalid_properties.push('invalid value for "discount", must be greater than or equal to 0.')
      end

      if @net.nil?
        invalid_properties.push('invalid value for "net", net cannot be nil.')
      end

      if @net < 0
        invalid_properties.push('invalid value for "net", must be greater than or equal to 0.')
      end

      if @breakdown.nil?
        invalid_properties.push('invalid value for "breakdown", breakdown cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @gross.nil?
      return false if @gross < 0
      return false if @discount.nil?
      return false if @discount < 0
      return false if @net.nil?
      return false if @net < 0
      return false if @breakdown.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] gross Value to be assigned
    def gross=(gross)
      if gross.nil?
        fail ArgumentError, 'gross cannot be nil'
      end

      if gross < 0
        fail ArgumentError, 'invalid value for "gross", must be greater than or equal to 0.'
      end

      @gross = gross
    end

    # Custom attribute writer method with validation
    # @param [Object] discount Value to be assigned
    def discount=(discount)
      if discount.nil?
        fail ArgumentError, 'discount cannot be nil'
      end

      if discount < 0
        fail ArgumentError, 'invalid value for "discount", must be greater than or equal to 0.'
      end

      @discount = discount
    end

    # Custom attribute writer method with validation
    # @param [Object] net Value to be assigned
    def net=(net)
      if net.nil?
        fail ArgumentError, 'net cannot be nil'
      end

      if net < 0
        fail ArgumentError, 'invalid value for "net", must be greater than or equal to 0.'
      end

      @net = net
    end

    # Custom attribute writer method with validation
    # @param [Object] breakdown Value to be assigned
    def breakdown=(breakdown)
      if breakdown.nil?
        fail ArgumentError, 'breakdown cannot be nil'
      end

      @breakdown = breakdown
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          gross == o.gross &&
          discount == o.discount &&
          net == o.net &&
          breakdown == o.breakdown
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [gross, discount, net, breakdown].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
