=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  module LineItem
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'DigitalGoodsLineItem',
          :'DonationLineItem',
          :'FoodBeverageLineItem',
          :'OtherLineItem',
          :'PhysicalGoodsLineItem',
          :'ServiceLineItem',
          :'TicketLineItem'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'category'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'digital_goods' => :'DigitalGoodsLineItem',
          :'donation' => :'DonationLineItem',
          :'food_beverage' => :'FoodBeverageLineItem',
          :'other' => :'OtherLineItem',
          :'physical_goods' => :'PhysicalGoodsLineItem',
          :'service' => :'ServiceLineItem',
          :'ticket' => :'TicketLineItem'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        MaytesApiClient.const_get(klass).build_from_hash(data)
      end
    end
  end

end
