=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  class PhysicalGoodsLineItem < ApiModelBase
    attr_accessor :item_ref

    attr_accessor :parent_ref

    attr_accessor :sku

    attr_accessor :name

    attr_accessor :description

    attr_accessor :image_url

    attr_accessor :quantity

    attr_accessor :unit_price

    attr_accessor :currency

    attr_accessor :category

    attr_accessor :custom_data

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'item_ref' => :'item_ref',
        :'parent_ref' => :'parent_ref',
        :'sku' => :'sku',
        :'name' => :'name',
        :'description' => :'description',
        :'image_url' => :'image_url',
        :'quantity' => :'quantity',
        :'unit_price' => :'unit_price',
        :'currency' => :'currency',
        :'category' => :'category',
        :'custom_data' => :'custom_data'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'item_ref' => :'String',
        :'parent_ref' => :'String',
        :'sku' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'image_url' => :'String',
        :'quantity' => :'Integer',
        :'unit_price' => :'Integer',
        :'currency' => :'String',
        :'category' => :'String',
        :'custom_data' => :'PhysicalGoodsCustomData'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'parent_ref',
        :'sku',
        :'description',
        :'image_url',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MaytesApiClient::PhysicalGoodsLineItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MaytesApiClient::PhysicalGoodsLineItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'item_ref')
        self.item_ref = attributes[:'item_ref']
      else
        self.item_ref = nil
      end

      if attributes.key?(:'parent_ref')
        self.parent_ref = attributes[:'parent_ref']
      end

      if attributes.key?(:'sku')
        self.sku = attributes[:'sku']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      else
        self.quantity = nil
      end

      if attributes.key?(:'unit_price')
        self.unit_price = attributes[:'unit_price']
      else
        self.unit_price = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      else
        self.category = nil
      end

      if attributes.key?(:'custom_data')
        self.custom_data = attributes[:'custom_data']
      else
        self.custom_data = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @item_ref.nil?
        invalid_properties.push('invalid value for "item_ref", item_ref cannot be nil.')
      end

      if @item_ref.to_s.length < 1
        invalid_properties.push('invalid value for "item_ref", the character length must be greater than or equal to 1.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if @quantity.nil?
        invalid_properties.push('invalid value for "quantity", quantity cannot be nil.')
      end

      if @quantity <= 0
        invalid_properties.push('invalid value for "quantity", must be greater than 0.')
      end

      if @unit_price.nil?
        invalid_properties.push('invalid value for "unit_price", unit_price cannot be nil.')
      end

      if @unit_price < 0
        invalid_properties.push('invalid value for "unit_price", must be greater than or equal to 0.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if @currency !~ pattern
        invalid_properties.push("invalid value for \"currency\", must conform to the pattern #{pattern}.")
      end

      if @category.nil?
        invalid_properties.push('invalid value for "category", category cannot be nil.')
      end

      if @custom_data.nil?
        invalid_properties.push('invalid value for "custom_data", custom_data cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @item_ref.nil?
      return false if @item_ref.to_s.length < 1
      return false if @name.nil?
      return false if @name.to_s.length < 1
      return false if @quantity.nil?
      return false if @quantity <= 0
      return false if @unit_price.nil?
      return false if @unit_price < 0
      return false if @currency.nil?
      return false if @currency !~ Regexp.new(/^[A-Z]{3}$/)
      return false if @category.nil?
      category_validator = EnumAttributeValidator.new('String', ["physical_goods"])
      return false unless category_validator.valid?(@category)
      return false if @custom_data.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] item_ref Value to be assigned
    def item_ref=(item_ref)
      if item_ref.nil?
        fail ArgumentError, 'item_ref cannot be nil'
      end

      if item_ref.to_s.length < 1
        fail ArgumentError, 'invalid value for "item_ref", the character length must be greater than or equal to 1.'
      end

      @item_ref = item_ref
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] quantity Value to be assigned
    def quantity=(quantity)
      if quantity.nil?
        fail ArgumentError, 'quantity cannot be nil'
      end

      if quantity <= 0
        fail ArgumentError, 'invalid value for "quantity", must be greater than 0.'
      end

      @quantity = quantity
    end

    # Custom attribute writer method with validation
    # @param [Object] unit_price Value to be assigned
    def unit_price=(unit_price)
      if unit_price.nil?
        fail ArgumentError, 'unit_price cannot be nil'
      end

      if unit_price < 0
        fail ArgumentError, 'invalid value for "unit_price", must be greater than or equal to 0.'
      end

      @unit_price = unit_price
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if currency !~ pattern
        fail ArgumentError, "invalid value for \"currency\", must conform to the pattern #{pattern}."
      end

      @currency = currency
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] category Object to be assigned
    def category=(category)
      validator = EnumAttributeValidator.new('String', ["physical_goods"])
      unless validator.valid?(category)
        fail ArgumentError, "invalid value for \"category\", must be one of #{validator.allowable_values}."
      end
      @category = category
    end

    # Custom attribute writer method with validation
    # @param [Object] custom_data Value to be assigned
    def custom_data=(custom_data)
      if custom_data.nil?
        fail ArgumentError, 'custom_data cannot be nil'
      end

      @custom_data = custom_data
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          item_ref == o.item_ref &&
          parent_ref == o.parent_ref &&
          sku == o.sku &&
          name == o.name &&
          description == o.description &&
          image_url == o.image_url &&
          quantity == o.quantity &&
          unit_price == o.unit_price &&
          currency == o.currency &&
          category == o.category &&
          custom_data == o.custom_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [item_ref, parent_ref, sku, name, description, image_url, quantity, unit_price, currency, category, custom_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
