=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  class Settlement < ApiModelBase
    attr_accessor :uuid

    attr_accessor :merchant_uuid

    attr_accessor :period_from

    attr_accessor :period_to

    attr_accessor :idempotency_key

    attr_accessor :merchant_payable_amount

    attr_accessor :settled_amount

    attr_accessor :currency

    attr_accessor :status

    attr_accessor :stripe_transfer_id

    attr_accessor :notes

    attr_accessor :settled_at

    attr_accessor :expires_at

    attr_accessor :reviewed_by_user_uuid

    attr_accessor :reviewed_at

    attr_accessor :rejection_reason

    attr_accessor :created_at

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'merchant_uuid' => :'merchant_uuid',
        :'period_from' => :'period_from',
        :'period_to' => :'period_to',
        :'idempotency_key' => :'idempotency_key',
        :'merchant_payable_amount' => :'merchant_payable_amount',
        :'settled_amount' => :'settled_amount',
        :'currency' => :'currency',
        :'status' => :'status',
        :'stripe_transfer_id' => :'stripe_transfer_id',
        :'notes' => :'notes',
        :'settled_at' => :'settled_at',
        :'expires_at' => :'expires_at',
        :'reviewed_by_user_uuid' => :'reviewed_by_user_uuid',
        :'reviewed_at' => :'reviewed_at',
        :'rejection_reason' => :'rejection_reason',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'merchant_uuid' => :'String',
        :'period_from' => :'Time',
        :'period_to' => :'Time',
        :'idempotency_key' => :'String',
        :'merchant_payable_amount' => :'Integer',
        :'settled_amount' => :'Integer',
        :'currency' => :'String',
        :'status' => :'String',
        :'stripe_transfer_id' => :'String',
        :'notes' => :'String',
        :'settled_at' => :'Time',
        :'expires_at' => :'Time',
        :'reviewed_by_user_uuid' => :'String',
        :'reviewed_at' => :'Time',
        :'rejection_reason' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'stripe_transfer_id',
        :'notes',
        :'settled_at',
        :'expires_at',
        :'reviewed_by_user_uuid',
        :'reviewed_at',
        :'rejection_reason',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MaytesApiClient::Settlement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MaytesApiClient::Settlement`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      else
        self.uuid = nil
      end

      if attributes.key?(:'merchant_uuid')
        self.merchant_uuid = attributes[:'merchant_uuid']
      else
        self.merchant_uuid = nil
      end

      if attributes.key?(:'period_from')
        self.period_from = attributes[:'period_from']
      else
        self.period_from = nil
      end

      if attributes.key?(:'period_to')
        self.period_to = attributes[:'period_to']
      else
        self.period_to = nil
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      else
        self.idempotency_key = nil
      end

      if attributes.key?(:'merchant_payable_amount')
        self.merchant_payable_amount = attributes[:'merchant_payable_amount']
      else
        self.merchant_payable_amount = nil
      end

      if attributes.key?(:'settled_amount')
        self.settled_amount = attributes[:'settled_amount']
      else
        self.settled_amount = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'stripe_transfer_id')
        self.stripe_transfer_id = attributes[:'stripe_transfer_id']
      else
        self.stripe_transfer_id = nil
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      else
        self.notes = nil
      end

      if attributes.key?(:'settled_at')
        self.settled_at = attributes[:'settled_at']
      else
        self.settled_at = nil
      end

      if attributes.key?(:'expires_at')
        self.expires_at = attributes[:'expires_at']
      else
        self.expires_at = nil
      end

      if attributes.key?(:'reviewed_by_user_uuid')
        self.reviewed_by_user_uuid = attributes[:'reviewed_by_user_uuid']
      else
        self.reviewed_by_user_uuid = nil
      end

      if attributes.key?(:'reviewed_at')
        self.reviewed_at = attributes[:'reviewed_at']
      else
        self.reviewed_at = nil
      end

      if attributes.key?(:'rejection_reason')
        self.rejection_reason = attributes[:'rejection_reason']
      else
        self.rejection_reason = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @uuid.nil?
        invalid_properties.push('invalid value for "uuid", uuid cannot be nil.')
      end

      if @merchant_uuid.nil?
        invalid_properties.push('invalid value for "merchant_uuid", merchant_uuid cannot be nil.')
      end

      if @period_from.nil?
        invalid_properties.push('invalid value for "period_from", period_from cannot be nil.')
      end

      if @period_to.nil?
        invalid_properties.push('invalid value for "period_to", period_to cannot be nil.')
      end

      if @idempotency_key.nil?
        invalid_properties.push('invalid value for "idempotency_key", idempotency_key cannot be nil.')
      end

      if @merchant_payable_amount.nil?
        invalid_properties.push('invalid value for "merchant_payable_amount", merchant_payable_amount cannot be nil.')
      end

      if @settled_amount.nil?
        invalid_properties.push('invalid value for "settled_amount", settled_amount cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @currency.to_s.length > 3
        invalid_properties.push('invalid value for "currency", the character length must be smaller than or equal to 3.')
      end

      if @currency.to_s.length < 3
        invalid_properties.push('invalid value for "currency", the character length must be greater than or equal to 3.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @uuid.nil?
      return false if @merchant_uuid.nil?
      return false if @period_from.nil?
      return false if @period_to.nil?
      return false if @idempotency_key.nil?
      return false if @merchant_payable_amount.nil?
      return false if @settled_amount.nil?
      return false if @currency.nil?
      return false if @currency.to_s.length > 3
      return false if @currency.to_s.length < 3
      return false if @status.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] uuid Value to be assigned
    def uuid=(uuid)
      if uuid.nil?
        fail ArgumentError, 'uuid cannot be nil'
      end

      @uuid = uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_uuid Value to be assigned
    def merchant_uuid=(merchant_uuid)
      if merchant_uuid.nil?
        fail ArgumentError, 'merchant_uuid cannot be nil'
      end

      @merchant_uuid = merchant_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] period_from Value to be assigned
    def period_from=(period_from)
      if period_from.nil?
        fail ArgumentError, 'period_from cannot be nil'
      end

      @period_from = period_from
    end

    # Custom attribute writer method with validation
    # @param [Object] period_to Value to be assigned
    def period_to=(period_to)
      if period_to.nil?
        fail ArgumentError, 'period_to cannot be nil'
      end

      @period_to = period_to
    end

    # Custom attribute writer method with validation
    # @param [Object] idempotency_key Value to be assigned
    def idempotency_key=(idempotency_key)
      if idempotency_key.nil?
        fail ArgumentError, 'idempotency_key cannot be nil'
      end

      @idempotency_key = idempotency_key
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_payable_amount Value to be assigned
    def merchant_payable_amount=(merchant_payable_amount)
      if merchant_payable_amount.nil?
        fail ArgumentError, 'merchant_payable_amount cannot be nil'
      end

      @merchant_payable_amount = merchant_payable_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] settled_amount Value to be assigned
    def settled_amount=(settled_amount)
      if settled_amount.nil?
        fail ArgumentError, 'settled_amount cannot be nil'
      end

      @settled_amount = settled_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      if currency.to_s.length > 3
        fail ArgumentError, 'invalid value for "currency", the character length must be smaller than or equal to 3.'
      end

      if currency.to_s.length < 3
        fail ArgumentError, 'invalid value for "currency", the character length must be greater than or equal to 3.'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uuid == o.uuid &&
          merchant_uuid == o.merchant_uuid &&
          period_from == o.period_from &&
          period_to == o.period_to &&
          idempotency_key == o.idempotency_key &&
          merchant_payable_amount == o.merchant_payable_amount &&
          settled_amount == o.settled_amount &&
          currency == o.currency &&
          status == o.status &&
          stripe_transfer_id == o.stripe_transfer_id &&
          notes == o.notes &&
          settled_at == o.settled_at &&
          expires_at == o.expires_at &&
          reviewed_by_user_uuid == o.reviewed_by_user_uuid &&
          reviewed_at == o.reviewed_at &&
          rejection_reason == o.rejection_reason &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, merchant_uuid, period_from, period_to, idempotency_key, merchant_payable_amount, settled_amount, currency, status, stripe_transfer_id, notes, settled_at, expires_at, reviewed_by_user_uuid, reviewed_at, rejection_reason, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
