=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module MaytesApiClient
  class TicketCustomData < ApiModelBase
    attr_accessor :event_id

    attr_accessor :event_start_at

    attr_accessor :timezone

    attr_accessor :ticket_class

    attr_accessor :name

    attr_accessor :event_end_at

    attr_accessor :delivery_mode

    attr_accessor :venue_name

    attr_accessor :venue_address

    attr_accessor :seating

    attr_accessor :terms_url

    attr_accessor :attendee_required

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'event_id' => :'event_id',
        :'event_start_at' => :'event_start_at',
        :'timezone' => :'timezone',
        :'ticket_class' => :'ticket_class',
        :'name' => :'name',
        :'event_end_at' => :'event_end_at',
        :'delivery_mode' => :'delivery_mode',
        :'venue_name' => :'venue_name',
        :'venue_address' => :'venue_address',
        :'seating' => :'seating',
        :'terms_url' => :'terms_url',
        :'attendee_required' => :'attendee_required'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'event_id' => :'String',
        :'event_start_at' => :'Time',
        :'timezone' => :'String',
        :'ticket_class' => :'String',
        :'name' => :'String',
        :'event_end_at' => :'Time',
        :'delivery_mode' => :'String',
        :'venue_name' => :'String',
        :'venue_address' => :'Hash<String, Object>',
        :'seating' => :'TicketSeating',
        :'terms_url' => :'String',
        :'attendee_required' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MaytesApiClient::TicketCustomData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MaytesApiClient::TicketCustomData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'event_id')
        self.event_id = attributes[:'event_id']
      else
        self.event_id = nil
      end

      if attributes.key?(:'event_start_at')
        self.event_start_at = attributes[:'event_start_at']
      else
        self.event_start_at = nil
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      else
        self.timezone = nil
      end

      if attributes.key?(:'ticket_class')
        self.ticket_class = attributes[:'ticket_class']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'event_end_at')
        self.event_end_at = attributes[:'event_end_at']
      end

      if attributes.key?(:'delivery_mode')
        self.delivery_mode = attributes[:'delivery_mode']
      end

      if attributes.key?(:'venue_name')
        self.venue_name = attributes[:'venue_name']
      end

      if attributes.key?(:'venue_address')
        if (value = attributes[:'venue_address']).is_a?(Hash)
          self.venue_address = value
        end
      end

      if attributes.key?(:'seating')
        self.seating = attributes[:'seating']
      end

      if attributes.key?(:'terms_url')
        self.terms_url = attributes[:'terms_url']
      end

      if attributes.key?(:'attendee_required')
        self.attendee_required = attributes[:'attendee_required']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @event_id.nil?
        invalid_properties.push('invalid value for "event_id", event_id cannot be nil.')
      end

      if @event_start_at.nil?
        invalid_properties.push('invalid value for "event_start_at", event_start_at cannot be nil.')
      end

      if @timezone.nil?
        invalid_properties.push('invalid value for "timezone", timezone cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @event_id.nil?
      return false if @event_start_at.nil?
      return false if @timezone.nil?
      delivery_mode_validator = EnumAttributeValidator.new('String', ["email", "sms", "post", "at_venue"])
      return false unless delivery_mode_validator.valid?(@delivery_mode)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] event_id Value to be assigned
    def event_id=(event_id)
      if event_id.nil?
        fail ArgumentError, 'event_id cannot be nil'
      end

      @event_id = event_id
    end

    # Custom attribute writer method with validation
    # @param [Object] event_start_at Value to be assigned
    def event_start_at=(event_start_at)
      if event_start_at.nil?
        fail ArgumentError, 'event_start_at cannot be nil'
      end

      @event_start_at = event_start_at
    end

    # Custom attribute writer method with validation
    # @param [Object] timezone Value to be assigned
    def timezone=(timezone)
      if timezone.nil?
        fail ArgumentError, 'timezone cannot be nil'
      end

      @timezone = timezone
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] delivery_mode Object to be assigned
    def delivery_mode=(delivery_mode)
      validator = EnumAttributeValidator.new('String', ["email", "sms", "post", "at_venue"])
      unless validator.valid?(delivery_mode)
        fail ArgumentError, "invalid value for \"delivery_mode\", must be one of #{validator.allowable_values}."
      end
      @delivery_mode = delivery_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          event_id == o.event_id &&
          event_start_at == o.event_start_at &&
          timezone == o.timezone &&
          ticket_class == o.ticket_class &&
          name == o.name &&
          event_end_at == o.event_end_at &&
          delivery_mode == o.delivery_mode &&
          venue_name == o.venue_name &&
          venue_address == o.venue_address &&
          seating == o.seating &&
          terms_url == o.terms_url &&
          attendee_required == o.attendee_required
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [event_id, event_start_at, timezone, ticket_class, name, event_end_at, delivery_mode, venue_name, venue_address, seating, terms_url, attendee_required].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
