# -*- encoding: utf-8 -*-

=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "maytes_api_client/version"

Gem::Specification.new do |s|
  s.name        = "maytes-api-client-rb"
  s.version     = MaytesApiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Maytes"]
  s.email       = []
  s.homepage    = "https://developers.maytes.co"
  s.summary     = "Official Ruby client for the Maytes API"
  s.description = "Official Ruby client for the Maytes API — create, capture and cancel checkouts, with OAuth2 token management and webhook signature verification."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = { "homepage_uri" => "https://developers.maytes.co", "source_code_uri" => "https://github.com/kttipay/maytes-api-client-rb", "bug_tracker_uri" => "https://github.com/kttipay/maytes-api-client-rb/issues", "documentation_uri" => "https://developers.maytes.co" }

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
