=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MaytesApiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = MaytesApiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(MaytesApiClient::DefaultApi)
    end
  end

  # unit tests for cancel_checkout
  # Cancel authorized checkout
  # @param checkout_uuid 
  # @param cancel_checkout_request 
  # @param [Hash] opts the optional parameters
  # @return [CancelCheckoutResponse]
  describe 'cancel_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for capture_checkout
  # Capture authorized checkout
  # @param checkout_uuid 
  # @param capture_checkout_request 
  # @param [Hash] opts the optional parameters
  # @return [CaptureCheckoutResponse]
  describe 'capture_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_checkout
  # Create a new checkout
  # @param create_checkout_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateCheckoutResponse]
  describe 'create_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_checkout
  # Get checkout details
  # @param checkout_uuid 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :merchant_order_id 
  # @return [GetCheckoutResponse]
  describe 'get_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_health
  # Health check
  # @param [Hash] opts the optional parameters
  # @return [HealthResponse]
  describe 'get_health test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_o_auth_token
  # Issue an access token
  # @param o_auth_token_request 
  # @param [Hash] opts the optional parameters
  # @return [OAuthTokenResponse]
  describe 'get_o_auth_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_settlement
  # Get a settlement by UUID
  # @param uuid Settlement UUID
  # @param [Hash] opts the optional parameters
  # @return [GetSettlementResponse]
  describe 'get_settlement test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_settlements
  # List settlements for this merchant
  # Returns settlements for the authenticated merchant. Default sort: created_at ASC.
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :offset Pagination offset (default 0)
  # @option opts [Object] :limit Max records to return (default 50, max 200)
  # @option opts [String] :sort_dir Sort direction (default: asc)
  # @option opts [String] :sort_by Field to sort by (default: created_at)
  # @option opts [Object] :created_before Include settlements created at or before this ISO-8601 timestamp
  # @option opts [Object] :created_after Include settlements created at or after this ISO-8601 timestamp
  # @option opts [String] :status Filter by status
  # @return [ListSettlementsResponse]
  describe 'list_settlements test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for refund_checkout
  # Refund a captured checkout
  # Initiates a full refund of the captured payment. Returns 204 immediately; Stripe confirms asynchronously via webhook. Poll GET /checkouts/:uuid for status and refund details.
  # @param checkout_uuid 
  # @param create_refund_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'refund_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
