=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MaytesApiClient::CancelCheckoutRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MaytesApiClient::CancelCheckoutRequest do
  #let(:instance) { MaytesApiClient::CancelCheckoutRequest.new }

  describe 'test an instance of CancelCheckoutRequest' do
    it 'should create an instance of CancelCheckoutRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MaytesApiClient::CancelCheckoutRequest)
    end
  end

  describe 'test attribute "merchant_order_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
