=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MaytesApiClient::PhysicalGoodsCustomData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MaytesApiClient::PhysicalGoodsCustomData do
  #let(:instance) { MaytesApiClient::PhysicalGoodsCustomData.new }

  describe 'test an instance of PhysicalGoodsCustomData' do
    it 'should create an instance of PhysicalGoodsCustomData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MaytesApiClient::PhysicalGoodsCustomData)
    end
  end

  describe 'test attribute "product_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "comments"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
