=begin
#Maytes API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'maytes_api_client/api_client'
require 'maytes_api_client/api_error'
require 'maytes_api_client/api_model_base'
require 'maytes_api_client/version'
require 'maytes_api_client/configuration'

# Models
require 'maytes_api_client/models/cancel_checkout409_response'
require 'maytes_api_client/models/cancel_checkout_request'
require 'maytes_api_client/models/cancel_checkout_response'
require 'maytes_api_client/models/capture_checkout409_response'
require 'maytes_api_client/models/capture_checkout422_response'
require 'maytes_api_client/models/capture_checkout_request'
require 'maytes_api_client/models/capture_checkout_response'
require 'maytes_api_client/models/checkout'
require 'maytes_api_client/models/checkout_cancelled'
require 'maytes_api_client/models/checkout_captured'
require 'maytes_api_client/models/checkout_created'
require 'maytes_api_client/models/checkout_discount'
require 'maytes_api_client/models/checkout_fee'
require 'maytes_api_client/models/create_checkout401_response'
require 'maytes_api_client/models/create_checkout409_response'
require 'maytes_api_client/models/create_checkout422_response'
require 'maytes_api_client/models/create_checkout_request'
require 'maytes_api_client/models/create_checkout_response'
require 'maytes_api_client/models/create_refund_request'
require 'maytes_api_client/models/customer_data'
require 'maytes_api_client/models/digital_goods_custom_data'
require 'maytes_api_client/models/digital_goods_line_item'
require 'maytes_api_client/models/donation_line_item'
require 'maytes_api_client/models/error_response_dto'
require 'maytes_api_client/models/fee'
require 'maytes_api_client/models/fee_breakdown_line'
require 'maytes_api_client/models/food_beverage_line_item'
require 'maytes_api_client/models/get_checkout404_response'
require 'maytes_api_client/models/get_checkout422_response'
require 'maytes_api_client/models/get_checkout_response'
require 'maytes_api_client/models/get_settlement_response'
require 'maytes_api_client/models/health_response'
require 'maytes_api_client/models/line_item'
require 'maytes_api_client/models/list_settlements_response'
require 'maytes_api_client/models/o_auth_token_request'
require 'maytes_api_client/models/o_auth_token_response'
require 'maytes_api_client/models/other_line_item'
require 'maytes_api_client/models/physical_goods_custom_data'
require 'maytes_api_client/models/physical_goods_line_item'
require 'maytes_api_client/models/refund_checkout402_response'
require 'maytes_api_client/models/refund_checkout409_response'
require 'maytes_api_client/models/service_custom_data'
require 'maytes_api_client/models/service_line_item'
require 'maytes_api_client/models/settlement'
require 'maytes_api_client/models/tax'
require 'maytes_api_client/models/ticket_custom_data'
require 'maytes_api_client/models/ticket_line_item'
require 'maytes_api_client/models/ticket_seating'

# APIs
require 'maytes_api_client/api/default_api'

module MaytesApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   MaytesApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end

# Hand-written extra (post-processed in by sdks/backend-sdk/bin/postprocess-ruby.sh)
require 'maytes_api_client/managed_client'

# Hand-written extra (post-processed in by sdks/backend-sdk/bin/postprocess-ruby.sh)
require 'maytes_api_client/webhook_verifier'
